//! Routing regression tests using real PBF-derived graph data.
//!
//! These tests load a cached graph (built from rhone-alpes PBF) and verify
//! that routing between known waypoints produces consistent results.
//! This catches regressions in PBF parsing, graph construction, or routing.
//!
//! Requires: data/cache/*.bin (generated by backend_partial on first request)

use backend::{
    engine::RouteEngine,
    geo_utils::approximate_distance_km,
    graph::GraphFile,
    models::{Coordinate, RouteRequest},
};
use std::path::Path;
use std::sync::LazyLock;

/// Shared engine loaded once for all tests (262 MB graph)
static ENGINE: LazyLock<Option<RouteEngine>> = LazyLock::new(|| {
    let graph = load_cached_graph()?;
    eprintln!(
        "Graph loaded: {} nodes, {} edges",
        graph.nodes.len(),
        graph.edges.len()
    );
    RouteEngine::from_graph_file(graph).ok()
});

/// Find a .bin cache file in data/cache/ directory
fn load_cached_graph() -> Option<GraphFile> {
    // cargo test runs from the package directory (backend/)
    for dir in ["data/cache", "../data/cache"] {
        let p = Path::new(dir);
        if p.exists() {
            if let Some(graph) = load_first_graph(p) {
                return Some(graph);
            }
        }
    }
    None
}

fn load_first_graph(dir: &Path) -> Option<GraphFile> {
    // Try .bin first, then .json.zst, then .json
    for ext in ["bin", "json.zst", "json"] {
        let entries: Vec<_> = std::fs::read_dir(dir)
            .ok()?
            .filter_map(|e| e.ok())
            .filter(|e| {
                e.path()
                    .to_str()
                    .is_some_and(|s| s.ends_with(&format!(".{}", ext)))
            })
            .collect();

        if let Some(entry) = entries.first() {
            let path = entry.path();
            eprintln!("Loading cached graph: {}", path.display());
            match GraphFile::read_from_path(&path) {
                Ok(g) => return Some(g),
                Err(e) => {
                    eprintln!("ERROR reading {}: {}", path.display(), e);
                    continue;
                }
            }
        }
    }
    None
}

fn engine() -> &'static RouteEngine {
    ENGINE
        .as_ref()
        .expect("No cached graph in data/cache/ — run backend first")
}

/// Known waypoints in the Beaujolais area (from real user requests in logs)
const WAYPOINTS: [(f64, f64); 7] = [
    (45.93062728421614, 4.577789685898068),  // Start/End (loop)
    (45.93344507128484, 4.57832987125542),    // WP2
    (45.936225147548555, 4.57830286198714),   // WP3
    (45.940762602736186, 4.577897292752624),  // WP4
    (45.93918486782826, 4.575790569859919),   // WP5
    (45.93578507215992, 4.574521134271436),   // WP6
    (45.93052530908989, 4.577005986886917),   // WP7
];

#[test]
fn graph_has_expected_size() {
    let graph = match load_cached_graph() {
        Some(g) => g,
        None => {
            eprintln!("SKIPPED: no cached graph");
            return;
        }
    };

    assert!(
        graph.nodes.len() > 100_000,
        "Graph too small: {} nodes (expected >100k)",
        graph.nodes.len()
    );
    assert!(
        graph.edges.len() > 100_000,
        "Graph too small: {} edges (expected >100k)",
        graph.edges.len()
    );
}

#[test]
fn each_segment_finds_a_path() {
    let engine = engine();

    for i in 0..WAYPOINTS.len() - 1 {
        let (slat, slon) = WAYPOINTS[i];
        let (elat, elon) = WAYPOINTS[i + 1];

        let path = engine.find_path(&RouteRequest {
            start: Coordinate { lat: slat, lon: slon },
            end: Coordinate { lat: elat, lon: elon },
            w_pop: 1.0,
            w_paved: 1.0,
        });

        assert!(
            path.is_some(),
            "Segment {} -> {} should find a path",
            i,
            i + 1
        );

        let path = path.unwrap();
        assert!(
            path.len() >= 2,
            "Segment {} -> {}: path too short ({} points)",
            i,
            i + 1,
            path.len()
        );
    }
}

#[test]
fn full_loop_distance_is_stable() {
    let engine = engine();

    let mut full_path: Vec<Coordinate> = Vec::new();

    // All segments including closing the loop (WP7 -> WP1)
    let mut all_waypoints = WAYPOINTS.to_vec();
    all_waypoints.push(WAYPOINTS[0]);

    for i in 0..all_waypoints.len() - 1 {
        let (slat, slon) = all_waypoints[i];
        let (elat, elon) = all_waypoints[i + 1];

        let segment = engine
            .find_path(&RouteRequest {
                start: Coordinate { lat: slat, lon: slon },
                end: Coordinate { lat: elat, lon: elon },
                w_pop: 1.0,
                w_paved: 1.0,
            })
            .unwrap_or_else(|| panic!("No path for segment {} -> {}", i, i + 1));

        if full_path.is_empty() {
            full_path.extend_from_slice(&segment);
        } else {
            full_path.extend_from_slice(&segment[1..]);
        }
    }

    let distance_km = approximate_distance_km(&full_path);

    eprintln!(
        "Full loop: {} waypoints, {:.4} km",
        full_path.len(),
        distance_km
    );

    // Snapshot: 2.8513 km, 98 waypoints (established 2026-02-13)
    // 10% tolerance to catch major regressions but allow minor graph changes
    assert!(
        (distance_km - 2.8513).abs() < 0.30,
        "Loop distance regressed: {:.4} km (expected ~2.85 km, tolerance ±0.30)",
        distance_km
    );
    assert!(
        full_path.len() >= 50 && full_path.len() <= 200,
        "Path length regressed: {} points (expected ~98, range 50-200)",
        full_path.len()
    );

    eprintln!("REGRESSION_SNAPSHOT: distance_km = {:.10}", distance_km);
    eprintln!("REGRESSION_SNAPSHOT: path_len = {}", full_path.len());
}

#[test]
fn path_coordinates_stay_near_waypoints() {
    let engine = engine();

    for i in 0..WAYPOINTS.len() - 1 {
        let (slat, slon) = WAYPOINTS[i];
        let (elat, elon) = WAYPOINTS[i + 1];

        let path = engine
            .find_path(&RouteRequest {
                start: Coordinate { lat: slat, lon: slon },
                end: Coordinate { lat: elat, lon: elon },
                w_pop: 1.0,
                w_paved: 1.0,
            })
            .expect("path should exist");

        let start_dist = haversine_m(path[0].lat, path[0].lon, slat, slon);
        let end_dist = haversine_m(
            path[path.len() - 1].lat,
            path[path.len() - 1].lon,
            elat,
            elon,
        );

        // Snapped nodes should be within 200m of requested point
        assert!(
            start_dist < 200.0,
            "Segment {}: start snapped too far ({:.0}m)",
            i,
            start_dist
        );
        assert!(
            end_dist < 200.0,
            "Segment {}: end snapped too far ({:.0}m)",
            i,
            end_dist
        );
    }
}

fn haversine_m(lat1: f64, lon1: f64, lat2: f64, lon2: f64) -> f64 {
    let r = 6_371_000.0;
    let dlat = (lat2 - lat1).to_radians();
    let dlon = (lon2 - lon1).to_radians();
    let a = (dlat / 2.0).sin().powi(2)
        + lat1.to_radians().cos() * lat2.to_radians().cos() * (dlon / 2.0).sin().powi(2);
    r * 2.0 * a.sqrt().asin()
}
